global using Framework.Core;
global using Framework.Platform;
global using Framework.WebApi;
global using Microsoft.AspNetCore.Mvc;
global using PIHCM.Gen.Entities;
global using PIHCM.Gen.Enums;
global using PIHCM.Gen.Interfances;
global using SqlSugar;
global using System.ComponentModel;
